"""Compare results before and after fuzzy matching fix"""

print("=" * 80)
print("FUZZY MATCHING FIX - RESULTS COMPARISON")
print("=" * 80)

print("\nBEFORE (exact substring matching):")
print("  Subject coverage: 41/50 (82.0%)")
print("  Predicate coverage: 50/50 (100.0%)")
print("  Object coverage: 21/50 (42.0%)")
print("  Complete S+P+O: 18/50 (36.0%)")

print("\nAFTER (fuzzy token-level matching):")
print("  Subject coverage: 45/50 (90.0%)")
print("  Predicate coverage: 50/50 (100.0%)")
print("  Object coverage: 32/50 (64.0%)")
print("  Complete S+P+O: 28/50 (56.0%)")

print("\nIMPROVEMENTS:")
print("  Subject: +4 examples (+8.0%)")
print("  Predicate: no change (already perfect)")
print("  Object: +11 examples (+22.0%)")
print("  Complete S+P+O: +10 examples (+20.0%)")

print("\n" + "=" * 80)
print("KEY FIXES:")
print("=" * 80)
print("✓ Handles hyphen normalization: 'fine-grained' vs 'fine - grained'")
print("✓ Handles punctuation spacing: 'controllability,' vs 'controllability ,'")
print("✓ Token-level matching instead of exact substring")
print("✓ Allows small gaps (1-2 tokens) for punctuation")
print("✓ More robust to Stanza text normalization differences")

print("\n" + "=" * 80)
print("QUALITY ASSESSMENT:")
print("=" * 80)
print("✓ 56% complete S+P+O triplets (was 36%, target >50%)")
print("✓ 64% object coverage (was 42%, target >70% - close!)")
print("✓ 90% subject coverage (was 82%)")
print("✓ 100% predicate coverage (maintained)")

print("\nREADY FOR VALIDATION:")
print("User should review output.csv and validate semantic triplet quality.")
print("If satisfied, proceed to 250-chunk extraction, else iterate further.")
print("=" * 80)
